name: Frontend CI

on:
  pull_request:
  push:
    branches-ignore:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: frontend-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/frontend-ci.yml
